# Generated by Django 4.1.4 on 2022-12-27 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_userblasterrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasters',
            name='watchers',
            field=models.ManyToManyField(related_name='BlasterWatchers', through='store.UserBlasterRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blasters',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MyBlasters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userblasterrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True),
        ),
    ]
