# Generated by Django 4.1.4 on 2022-12-29 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_blasters_watchers_alter_blasters_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blasters',
            name='watchers',
        ),
        migrations.AddField(
            model_name='blasters',
            name='watched',
            field=models.ManyToManyField(related_name='bookwatched', through='store.UserBlasterRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
