# Generated by Django 4.1.4 on 2023-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_blasters_watchers_blasters_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasters',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
